# Generated by Django 4.1.3 on 2023-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_aiportproject_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='airport_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='airport_manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='airport_manager_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='area_center',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
