# Generated by Django 4.1.3 on 2023-04-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.CharField(blank=True, max_length=800, null=True)),
                ('bulletin_date', models.DateField(blank=True, null=True, verbose_name='bulletin_date')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('create_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='Bulletin/')),
                ('ext', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateField(blank=True, null=True, verbose_name='upload_date')),
                ('bulletin', models.ForeignKey(blank=True, db_column='bulletin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_file', to='dashboard.bulletin')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_date', models.DateTimeField(blank=True, null=True, verbose_name='upload_date')),
                ('create_by', models.CharField(blank=True, max_length=200, null=True)),
                ('bulletin', models.ForeignKey(blank=True, db_column='bulletin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_comment', to='dashboard.bulletin')),
            ],
        ),
        migrations.CreateModel(
            name='Aknowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_title', models.CharField(blank=True, max_length=200, null=True)),
                ('aknowledge_date', models.DateTimeField(blank=True, null=True, verbose_name='upload_date')),
                ('status', models.DateTimeField(blank=True, null=True, verbose_name='upload_date')),
                ('create_by', models.CharField(blank=True, max_length=200, null=True)),
                ('bulletin', models.ForeignKey(blank=True, db_column='bulletin_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulletin_viewed', to='dashboard.bulletin')),
            ],
        ),
    ]
