# Generated by Django 4.1.3 on 2023-04-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aknowledge',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
