# Generated by Django 4.1.3 on 2023-05-02 09:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_aiportproject_contract_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
