# Generated by Django 4.1.3 on 2023-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_aiportproject_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportproject',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
