# Generated by Django 4.1.3 on 2023-05-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_aiportproject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_apron',
            field=models.ImageField(blank=True, default='airports_photo/profile_apron.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='airports_photo/profile_photo.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_ptb',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_runway',
            field=models.ImageField(blank=True, default='airports_photo/profile_runway.png', upload_to='airports_photo/'),
        ),
    ]
