# Generated by Django 4.1.3 on 2023-05-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aiportprofile_profile_apron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='create_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='create_date'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='edit_date'),
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='create_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='create_date'),
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='edit_date'),
        ),
    ]
