# Generated by Django 4.1.3 on 2023-05-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_aiportprofile_apron_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
