# Generated by Django 4.1.3 on 2023-05-30 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_aiportproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiportproject',
            old_name='contract_rev',
            new_name='contract_rev1',
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='contract_rev2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
