# Generated by Django 3.2.12 on 2022-05-06 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='personal',
            field=models.OneToOneField(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds_personal', to='pds.personal'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('payroll', 'personal')},
        ),
    ]
