# Generated by Django 3.2.8 on 2022-06-17 02:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0004_auto_20220617_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pay_733_a',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
