# Generated by Django 3.2.8 on 2022-06-23 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pds', '0006_auto_20220617_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payroll',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds_payroll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
    ]
