# Generated by Django 3.2.8 on 2022-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0008_leave_spfleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='particulars',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
