# Generated by Django 3.2.8 on 2022-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0011_leave_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='spfleave',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
