# Generated by Django 3.2.8 on 2022-06-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0012_spfleave_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
