# Generated by Django 3.2.8 on 2022-06-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0013_alter_leave_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
