# Generated by Django 3.2.8 on 2022-06-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0014_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=200, null=True)),
                ('particulars', models.CharField(blank=True, max_length=200, null=True)),
                ('vacation_earned', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vacation_wpay', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vacation_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vacation_wopay', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sick_earned', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sick_wpay', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sick_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sick_wopay', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created')),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('leave', models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds_leave', to='pds.personal')),
            ],
        ),
    ]
