# Generated by Django 3.2.8 on 2022-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0015_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='job_level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Level'),
        ),
    ]
