# Generated by Django 3.2.8 on 2022-06-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0016_personal_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
