# Generated by Django 3.2.8 on 2022-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0018_auto_20220711_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='to'),
        ),
    ]
