# Generated by Django 3.2.8 on 2022-08-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0020_auto_20220803_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='salary_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
