# Generated by Django 3.2.8 on 2022-08-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0021_personal_salary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
