# Generated by Django 3.2.8 on 2022-08-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0023_alter_personal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='status',
        ),
    ]
