# Generated by Django 3.2.8 on 2022-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0027_personal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='actual_annual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='area_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='auth_annual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='dotr_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='gcg_sdd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='org_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='rate_perday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='tech_none',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='umid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(blank=True, default='For Approval', max_length=200, null=True),
        ),
    ]
