# Generated by Django 3.2.8 on 2022-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0028_auto_20220804_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='perma_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Permanet ZIP CODE'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='res_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Residence ZIP CODE'),
        ),
    ]
