# Generated by Django 3.2.8 on 2022-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0030_personal_edited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('gcg', models.CharField(max_length=200)),
                ('dotr', models.CharField(max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
