# Generated by Django 3.2.8 on 2022-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0031_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
