# Generated by Django 3.2.8 on 2022-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0033_alter_education_grad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='training_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
