# Generated by Django 3.2.8 on 2022-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0034_alter_learning_training_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='trainings/'),
        ),
    ]
