# Generated by Django 3.2.8 on 2022-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0035_alter_learning_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='date4',
            field=models.DateField(blank=True, null=True, verbose_name='Vax 4 Date'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dose4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='file4',
            field=models.ImageField(blank=True, null=True, upload_to='vaccine/'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='name4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='place4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
