# Generated by Django 3.2.8 on 2022-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0037_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
