# Generated by Django 3.2.8 on 2022-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0039_salarygrade_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
