# Generated by Django 3.2.8 on 2022-09-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0040_alter_position_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='disability_image',
            field=models.ImageField(blank=True, null=True, upload_to='otherinfo/'),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='soloparent_image',
            field=models.ImageField(blank=True, null=True, upload_to='otherinfo/'),
        ),
    ]
