# Generated by Django 3.2.8 on 2022-09-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0041_auto_20220922_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='contact_person_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='contact_relation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
