# Generated by Django 3.2.8 on 2022-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0043_personal_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='crime_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
