# Generated by Django 3.2.8 on 2022-09-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0044_otherinfo_crime_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='personal',
        ),
    ]
