# Generated by Django 3.2.8 on 2022-09-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0046_payroll_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateField(blank=True, null=True, verbose_name='post_date')),
                ('file', models.FileField(blank=True, null=True, upload_to='Post/')),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
