# Generated by Django 3.2.8 on 2022-09-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0048_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_by',
            new_name='create_by',
        ),
    ]
