# Generated by Django 3.2.8 on 2022-10-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0050_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
