# Generated by Django 3.2.8 on 2022-10-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0051_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
