# Generated by Django 3.2.8 on 2022-10-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0052_post_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferences',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
