# Generated by Django 3.2.8 on 2022-10-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0053_alter_refferences_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=800, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='post_date')),
                ('notify', models.ForeignKey(blank=True, db_column='personal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds_notify', to='pds.personal')),
            ],
        ),
    ]
