# Generated by Django 3.2.8 on 2022-11-11 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pds', '0054_notifytraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(blank=True, max_length=800, null=True)),
                ('title', models.CharField(blank=True, max_length=800, null=True)),
                ('body', models.CharField(blank=True, max_length=800, null=True)),
                ('status', models.CharField(blank=True, max_length=800, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='post_date')),
            ],
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_year_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_end_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_gift', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
