# Generated by Django 3.2.8 on 2022-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0055_bonuses_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuses',
            name='liquidation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bonuses',
            name='patcomc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bonuses',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
