# Generated by Django 3.2.8 on 2022-11-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0057_bonuses_total_year_end_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuses',
            name='total_year_end_bonus',
        ),
    ]
