# Generated by Django 3.2.8 on 2023-01-18 03:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0060_auto_20221227_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='january',
            name='pay_413_1a',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_413_1a',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
