# Generated by Django 3.2.8 on 2023-03-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pds', '0061_auto_20230118_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caapeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caapeu_pass', models.CharField(max_length=200)),
                ('caapeu', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_eu', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
