# Generated by Django 4.1.3 on 2023-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_aiportprofile_aiportproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='contract_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='fund_particulars',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='status_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
