# Generated by Django 4.1.3 on 2023-05-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_create_by_aiportprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='airport_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='firetruck',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='nav_iads',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='night_rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='operation_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
