# Generated by Django 4.1.3 on 2023-05-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_bulletin_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiportProject',
        ),
    ]
