# Generated by Django 4.1.3 on 2023-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_contract_rev_aiportproject_contract_rev1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='contract_rev1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='contract_rev2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
