# Generated by Django 4.1.3 on 2023-05-30 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_aiportproject_contract_rev1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='fund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True),
        ),
    ]
