# Generated by Django 4.1.3 on 2023-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_aiportproject_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='original',
            field=models.DateField(blank=True, null=True, verbose_name='original'),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='revised',
            field=models.DateField(blank=True, null=True, verbose_name='revised'),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
    ]
