# Generated by Django 4.0.4 on 2023-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_aiportprofile_airport_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_taxiway',
            field=models.ImageField(blank=True, default='airports_photo/profile_ataxiway.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_taxiway_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_taxiway.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_taxiway_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_taxiway.png', upload_to='airports_photo/'),
        ),
    ]
