# Generated by Django 4.0.4 on 2023-10-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_aiportproject_contract_amount_and_more'),
        ('dashboard', '0028_aiportprofile_profile_apron_1_and_more'),
    ]

    operations = [
    ]
