# Generated by Django 4.2.4 on 2023-10-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_merge_20231005_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_apron_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_apron.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_apron_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_apron.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_photo_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_photo.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_photo_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_photo.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_ptb_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_ptb_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_runway_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_runway.png', upload_to='airports_photo/'),
        ),
        migrations.AddField(
            model_name='aiportprofile',
            name='profile_runway_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_runway.png', upload_to='airports_photo/'),
        ),
        migrations.AlterField(
            model_name='aiportprofile',
            name='profile_taxiway',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
        migrations.AlterField(
            model_name='aiportprofile',
            name='profile_taxiway_1',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
        migrations.AlterField(
            model_name='aiportprofile',
            name='profile_taxiway_2',
            field=models.ImageField(blank=True, default='airports_photo/profile_ptb.png', upload_to='airports_photo/'),
        ),
    ]
